aws-vpc-move-ip: Removing comments and adjusting indentation

diff --git a/heartbeat/aws-vpc-move-ip b/heartbeat/aws-vpc-move-ip
--- a/heartbeat/aws-vpc-move-ip
+++ b/heartbeat/aws-vpc-move-ip
@@ -165,39 +165,28 @@ ec2ip_validate() {
 }
 
 ec2ip_monitor() {
-        # <fguilher> Empty local var </fguilher>
         MON_RES=""
-
 	if ocf_is_true ${OCF_RESKEY_monapi} || [ "$__OCF_ACTION" = "start" ] || ocf_is_probe; then
-           # <fguilher>
-           # Looping through $OCF_RESKEY_routing_table variable
-           # replace any "," with a single space
-           # </fguilher>
-           for rtb in $(echo $OCF_RESKEY_routing_table | sed -e 's/,/ /g'); do
-		ocf_log info "monitor: check routing table (API call) - $rtb"
-		cmd="$OCF_RESKEY_awscli --profile $OCF_RESKEY_profile --output text ec2 describe-route-tables --route-table-ids $rtb"
-		ocf_log debug "executing command: $cmd"
-		ROUTE_TO_INSTANCE="$($cmd | grep $OCF_RESKEY_ip | awk '{ print $3 }')"
-		if [ -z "$ROUTE_TO_INSTANCE" ]; then
-			ROUTE_TO_INSTANCE="<unknown>"
+		for rtb in $(echo $OCF_RESKEY_routing_table | sed -e 's/,/ /g'); do
+			ocf_log info "monitor: check routing table (API call) - $rtb"
+			cmd="$OCF_RESKEY_awscli --profile $OCF_RESKEY_profile --output text ec2 describe-route-tables --route-table-ids $rtb"
+			ocf_log debug "executing command: $cmd"
+			ROUTE_TO_INSTANCE="$($cmd | grep $OCF_RESKEY_ip | awk '{ print $3 }')"
+			if [ -z "$ROUTE_TO_INSTANCE" ]; then
+				ROUTE_TO_INSTANCE="<unknown>"
+			fi
+
+			if [ "$EC2_INSTANCE_ID" != "$ROUTE_TO_INSTANCE" ]; then 
+				ocf_log warn "not routed to this instance ($EC2_INSTANCE_ID) but to instance $ROUTE_TO_INSTANCE on $rtb"
+				MON_RES="$MON_RES $rtb"
+			fi
+			sleep 0.5
+		done
+
+		if [ ! -z "$MON_RES" ]; then
+			return $OCF_NOT_RUNNING
 		fi
 
-		if [ "$EC2_INSTANCE_ID" != "$ROUTE_TO_INSTANCE" ];then 
-			ocf_log warn "not routed to this instance ($EC2_INSTANCE_ID) but to instance $ROUTE_TO_INSTANCE"
-                        # <fguilher> Flag wrong rtb </fguilher>
-                        MON_RES="$MON_RES $rtb"
-		fi
-                # <fguilher> sleep for 0.5 second between rtbs </fguilher>
-                sleep 0.5
-           # <fguilher> End loop </fguilher>
-           done
-           # <fguilher> 
-           # if condition to detect if routing tables require correction
-           # and return error
-           # </fguilher>
-           if [ ! -z "$MON_RES" ]; then
-              return $OCF_NOT_RUNNING
-           fi
 	else
 		ocf_log debug "monitor: Enhanced Monitoring disabled - omitting API call"
 	fi
@@ -229,24 +218,17 @@ ec2ip_drop() {
 }
 
 ec2ip_get_and_configure() {
-	# Adjusting the routing table
-        # <fguilher>
-        # Looping through $OCF_RESKEY_routing_table variable
-        # replace any "," with a single space 
-        # </fguilher>
-        for rtb in $(echo $OCF_RESKEY_routing_table | sed -e 's/,/ /g'); do
-	   cmd="$OCF_RESKEY_awscli --profile $OCF_RESKEY_profile --output text ec2 replace-route --route-table-id $rtb --destination-cidr-block ${OCF_RESKEY_ip}/32 --instance-id $EC2_INSTANCE_ID"
-	   ocf_log debug "executing command: $cmd"
-	   $cmd
-	   rc=$?
-	   if [ "$rc" != 0 ]; then
-	   	   ocf_log warn "command failed, rc: $rc"
-		   return $OCF_ERR_GENERIC
-	   fi
-           # <fguilher> sleep for 0.5 between rtbs </fguilher>
-           sleep 1
-        # <fguilher> End loop </fguilher>
-        done
+	for rtb in $(echo $OCF_RESKEY_routing_table | sed -e 's/,/ /g'); do
+		cmd="$OCF_RESKEY_awscli --profile $OCF_RESKEY_profile --output text ec2 replace-route --route-table-id $rtb --destination-cidr-block ${OCF_RESKEY_ip}/32 --instance-id $EC2_INSTANCE_ID"
+		ocf_log debug "executing command: $cmd"
+		$cmd
+		rc=$?
+		if [ "$rc" != 0 ]; then
+			ocf_log warn "command failed, rc: $rc"
+			return $OCF_ERR_GENERIC
+		fi
+		sleep 0.5
+	done
 
 	# Reconfigure the local ip address
 	ec2ip_drop
